image: atlassian/default-image:2

options:
  docker: true
  size: 2x

pipelines:
  branches:
    feature/tmp:
      - step:
          name: Build and Push Docker Image
          image: atlassian/pipelines-awscli
          caches:
            - docker
          services:
            - docker
          deployment: deployment
          script:
            - docker build -t erp-back-backoffice-dev:latest -f Dockerfile-dev .
definitions:
  services:
    docker:
      memory: 4096